### ISSUE TITLE
Incompatible with svgo v1.1.0

### ISSUE THREAD

**Issue by ladjzero** [ben-eb/postcss-svgo#61]
The release of svgo v1.1.0 leads to such error

```
TypeError: Cannot read property 'path' of undefined
    at optimizeOnceCallback (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:48:29)
    at /home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:70:9
    at SAXParser.sax.onend (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo/svg2js.js:169:13)
    at emit (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:624:35)
    at end (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.write (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:975:14)
    at SAXParser.close (/home/chenzhuo/repos/activityengine/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo/svg2js.js:182:28)
    at SVGO._optimizeOnce (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:62:5)
    at Promise (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:55:14)
    at new Promise (<anonymous>)
    at SVGO.optimize (/home/chenzhuo/repos/activityengine/node_modules/svgo/lib/svgo.js:25:12)
    at decl.value.walk.node (/home/chenzhuo/repos/activityengine/node_modules/postcss-svgo/dist/index.js:69:28)
```

**Comment by ladjzero** [comment]
Relates to https://github.com/svg/svgo/issues/1030

**Comment by ladjzero** [comment]
Moved to https://github.com/cssnano/cssnano/issues/603
